eventTimeUtc=2004-12-23T14:59:30.900
eventLocation.latitude=-49.47264
eventLocation.longitude=161.35936
observer.latitude=-49.47264
observer.longitude=80.64064
eventSecondsPerFrame=2

sweep.count=2

sweep.0.pins=scenarios/macquarie-island/0/pins.csv
sweep.0.pings=scenarios/macquarie-island/0/pings.csv
sweep.0.propagation=scenarios/macquarie-island/0/propagation.csv
sweep.0.color=#FF0000
sweep.0.thickness=0.0025
sweep.0.fixedWidthMode=false
sweep.0.epicenter.latitude=-49.47264
sweep.0.epicenter.longitude=161.35936
sweep.0.outerPinSize=6
sweep.0.innerPinSize=12
sweep.0.pingOversize=18

sweep.1.pins=scenarios/macquarie-island/1/pins.csv
sweep.1.pings=scenarios/macquarie-island/1/pings.csv
sweep.1.propagation=scenarios/macquarie-island/1/propagation.csv
sweep.1.color=#00FF00
sweep.1.thickness=0.0025
sweep.1.fixedWidthMode=false
sweep.1.epicenter.latitude=-49.47264
sweep.1.epicenter.longitude=161.35936
sweep.1.outerPinSize=6
sweep.1.innerPinSize=12
sweep.1.pingOversize=18
