eventTimeUtc=2022-01-15T04:14:45.000
eventLocation.latitude=-20.568333728188723
eventLocation.longitude=-175.38028873791546
observer.latitude=0.0
observer.longitude=-100.0
eventSecondsPerFrame=274

sweep.count=1

sweep.0.pins=scenarios/hunga-tonga/0/pins.csv
sweep.0.pings=scenarios/hunga-tonga/0/pings.csv
sweep.0.propagation=scenarios/hunga-tonga/0/propagation.csv
sweep.0.color=#00FF00
sweep.0.thickness=0.0025
sweep.0.fixedWidthMode=false
sweep.0.epicenter.latitude=-20.568333728188723
sweep.0.epicenter.longitude=-175.38028873791546
sweep.0.outerPinSize=6
sweep.0.innerPinSize=12
sweep.0.pingOversize=18
